# 1. Menyertakan Suffix dan Prefix pada kolom `DataFrame`

In [1]:
# Import all of the necessary packages
import numpy as np
import pandas as pd

## Persiapan `DataFrame`

In [3]:
n_rows = 5
n_cols = 5
cols = tuple("ABCDE")

df = pd.DataFrame(np.random.randint(1, 10, size=(n_rows, n_cols)), columns=cols)
df

   A  B  C  D  E
0  2  2  7  4  9
1  4  5  3  2  2
2  9  4  2  3  4
3  5  5  6  1  5
4  1  3  5  3  7

## Menyertakan Suffix

In [5]:
df.add_suffix?

Signature: df.add_suffix(suffix: 'str', axis: 'Axis | None' = None) -> 'Self'
Docstring:
Suffix labels with string `suffix`.

For Series, the row labels are suffixed.
For DataFrame, the column labels are suffixed.

Parameters
----------
suffix : str
    The string to add after each label.
axis : {0 or 'index', 1 or 'columns', None}, default None
    Axis to add suffix on

    .. versionadded:: 2.0.0

Returns
-------
Series or DataFrame
    New Series or DataFrame with updated labels.

See Also
--------
Series.add_prefix: Prefix row labels with string `prefix`.
DataFrame.add_prefix: Prefix column labels with string `prefix`.

Examples
--------
>>> s = pd.Series([1, 2, 3, 4])
>>> s
0    1
1    2
2    3
3    4
dtype: int64

>>> s.add_suffix('_item')
0_item    1
1_item    2
2_item    3
3_item    4
dtype: int64

>>> df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': [3, 4, 5, 6]})
>>> df
   A  B
0  1  3
1  2  4
2  3  5
3  4  6

>>> df.add_suffix('_col')
     A_col  B_col
0       1       3
1       2       4
2       3       5
3       4       6
File:      c:\users\alima\anaconda3\lib\site-packages\pandas\core\generic.py
Type:      method

In [7]:
df.add_suffix("_col")

   A_col  B_col  C_col  D_col  E_col
0      2      2      7      4      9
1      4      5      3      2      2
2      9      4      2      3      4
3      5      5      6      1      5
4      1      3      5      3      7

## Menyertakan Prefix

In [10]:
df.add_prefix?

Signature: df.add_prefix(prefix: 'str', axis: 'Axis | None' = None) -> 'Self'
Docstring:
Prefix labels with string `prefix`.

For Series, the row labels are prefixed.
For DataFrame, the column labels are prefixed.

Parameters
----------
prefix : str
    The string to add before each label.
axis : {0 or 'index', 1 or 'columns', None}, default None
    Axis to add prefix on

    .. versionadded:: 2.0.0

Returns
-------
Series or DataFrame
    New Series or DataFrame with updated labels.

See Also
--------
Series.add_suffix: Suffix row labels with string `suffix`.
DataFrame.add_suffix: Suffix column labels with string `suffix`.

Examples
--------
>>> s = pd.Series([1, 2, 3, 4])
>>> s
0    1
1    2
2    3
3    4
dtype: int64

>>> s.add_prefix('item_')
item_0    1
item_1    2
item_2    3
item_3    4
dtype: int64

>>> df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': [3, 4, 5, 6]})
>>> df
   A  B
0  1  3
1  2  4
2  3  5
3  4  6

>>> df.add_prefix('col_')
     col_A  col_B
0       1       3
1       2       4
2       3       5
3       4       6
File:      c:\users\alima\anaconda3\lib\site-packages\pandas\core\generic.py
Type:      method

In [12]:
df.add_prefix("col_")

   col_A  col_B  col_C  col_D  col_E
0      2      2      7      4      9
1      4      5      3      2      2
2      9      4      2      3      4
3      5      5      6      1      5
4      1      3      5      3      7